"""init_db

Revision ID: 52e04495b5e7
Revises: 
Create Date: 2026-08-04 15:26:48.790616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e04495b5e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('hashed_pin', sa.String(length=255), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Users'))
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_Users_joined_at'), ['joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_Users_username'), ['username'], unique=True)

    op.create_table('Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_Accounts_user_id_Users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Accounts'))
    )
    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Accounts_user_id'), ['user_id'], unique=True)

    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), server_default='en', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_device_tokens_user_id_Users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tokens')),
    sa.UniqueConstraint('fcm_token', name=op.f('uq_device_tokens_fcm_token'))
    )
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_refresh_tokens_user_id_Users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_is_used'), ['is_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('Transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_account_id', sa.Integer(), nullable=False),
    sa.Column('receiver_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['Accounts.id'], name=op.f('fk_Transactions_receiver_account_id_Accounts')),
    sa.ForeignKeyConstraint(['sender_account_id'], ['Accounts.id'], name=op.f('fk_Transactions_sender_account_id_Accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Transactions'))
    )
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_Transactions_receiver_account_id'), ['receiver_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Transactions_sender_account_id'), ['sender_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Transactions_sender_account_id'))
        batch_op.drop_index(batch_op.f('ix_Transactions_receiver_account_id'))
        batch_op.drop_index(batch_op.f('ix_Transactions_created_at'))

    op.drop_table('Transactions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_is_used'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_tokens_id'))

    op.drop_table('device_tokens')
    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Accounts_user_id'))

    op.drop_table('Accounts')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_username'))
        batch_op.drop_index(batch_op.f('ix_Users_joined_at'))
        batch_op.drop_index(batch_op.f('ix_Users_email'))

    op.drop_table('Users')
    # ### end Alembic commands ###
