"""add new column avatar

Revision ID: 56eab9bdeab9
Revises: cccffdcf3356
Create Date: 2026-08-06 22:59:40.076468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56eab9bdeab9'
down_revision: Union[str, Sequence[str], None] = 'cccffdcf3356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Accounts_user_id_Users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Accounts_user_id_Users'), 'Users', ['user_id'], ['id'])

    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Transactions_receiver_account_id_Accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_Transactions_sender_account_id_Accounts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Transactions_sender_account_id_Accounts'), 'Accounts', ['sender_account_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_Transactions_receiver_account_id_Accounts'), 'Accounts', ['receiver_account_id'], ['id'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('avatar_key')

    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Transactions_receiver_account_id_Accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_Transactions_sender_account_id_Accounts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Transactions_sender_account_id_Accounts'), 'Accounts', ['sender_account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_Transactions_receiver_account_id_Accounts'), 'Accounts', ['receiver_account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Accounts_user_id_Users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Accounts_user_id_Users'), 'Users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
