"""add_cascade_to_transactions

Revision ID: cccffdcf3356
Revises: 52e04495b5e7
Create Date: 2026-08-04 15:41:22.115530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cccffdcf3356'
down_revision: Union[str, Sequence[str], None] = '52e04495b5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Transactions_sender_account_id_Accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_Transactions_receiver_account_id_Accounts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Transactions_receiver_account_id_Accounts'), 'Accounts', ['receiver_account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_Transactions_sender_account_id_Accounts'), 'Accounts', ['sender_account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Transactions_sender_account_id_Accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_Transactions_receiver_account_id_Accounts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Transactions_receiver_account_id_Accounts'), 'Accounts', ['receiver_account_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_Transactions_sender_account_id_Accounts'), 'Accounts', ['sender_account_id'], ['id'])

    # ### end Alembic commands ###
