"""add_locale_to_device_tokens

Revision ID: f8c594b3c481
Revises: c3c4dcdc0de5
Create Date: 2026-08-02 21:18:13.201216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c594b3c481'
down_revision: Union[str, Sequence[str], None] = 'c3c4dcdc0de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_tokens', sa.Column('locale', sa.String(), server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_tokens', 'locale')
    # ### end Alembic commands ###
